language: node_js
sudo: required
dist: trusty
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
node_js:
    - "8"
script: npm run karma
before_script:
    - npm install
